### ISSUE TITLE
RuntimeError: shape '[60, 60, -1]' is invalid for input of size 3072 in llff dataset

### ISSUE THREAD

**Issue by Zzzhewang** [cassiePython/CLIPNeRF#15]
Hi cassie,
thank you so much for your amazing works! i have encountered some problems when running the llff data set. It said that RuntimeError: shape '[60, 60, -1]' is invalid for input of size 3072. how can i fix this problem? Look forward for your replying. thanks again!
Traceback (most recent call last):
  File "run_nerf_clip.py", line 885, in <module>
    train()
  File "run_nerf_clip.py", line 805, in train
    rgb_img = rgb.view(sample_scale, sample_scale, -1)
RuntimeError: shape '[60, 60, -1]' is invalid for input of size 3072

**Comment by HannahHaensen** [comment]
@Zzzhewang were you able to fix this`? i faced the same problem

**Comment by cassiePython** [comment]
You should change the number of sampled rays to patch-size * patch-size.

**Comment by Jamie-Cheung** [comment]
> You should change the number of sampled rays to patch-size * patch-size.

Can you tell me the correct number of patch-size * patch-size.

**Comment by Jamie-Cheung** [comment]
> @Zzzhewang were you able to fix this`? i faced the same problem

were you able to fix this?

**Comment by wangfeng70117** [comment]
> You should change the number of sampled rays to patch-size * patch-size.

I also encountered the same problem, but I have no experience in using NeRF, and I need to use your project for comparative experiment. Can you help me know how to modify sampled rays？

**Comment by wangfeng70117** [comment]
> Hi cassie, thank you so much for your amazing works! i have encountered some problems when running the llff data set. It said that RuntimeError: shape '[60, 60, -1]' is invalid for input of size 3072. how can i fix this problem? Look forward for your replying. thanks again! Traceback (most recent call last): File "run_nerf_clip.py", line 885, in train() File "run_nerf_clip.py", line 805, in train rgb_img = rgb.view(sample_scale, sample_scale, -1) RuntimeError: shape '[60, 60, -1]' is invalid for input of size 3072

I also encountered the same problem, How did you solve the problem？
